### PR TITLE
Fix/0.3.1 - Bug fixes to 4 minor issues

### PR DESCRIPTION
**Pull request by AdamJelley**
Fixes for issues #1 #2 #5

### CODE REVIEW

**Review by alexcombessie — APPROVED** [review]

**Comment by alexcombessie** [comment]
Hola @AdamJelley would you have some time today to test on your local instance?

I think we should push this bugfix soon as 0.3.1. And then we can ship #6 #4 as part of a later release since this is less critical.

**Comment by alexcombessie** [comment]
@AdamJelley I tested again and it looks good to me!

@cperdigou is it ok for you to merge and publish this week? This PR should fix issues #1 #2 #5 #10. Thanks!

**Comment by alexcombessie** [comment]
@du-phan are you OK to review and merge? Then what is the process to push to the plugin store? Thanks!

**Comment by du-phan** [comment]
Hey can you bump the version on the json, I'll merge and handle the rest

**Pull request merged**
