### PR TITLE
Kubernetes support and misc enhancements

### PR DESCRIPTION
**Pull request by alexcombessie**
This should close issues #4 #6 #7 #11

### CODE REVIEW

**Comment by alexcombessie** [comment]
Hello @du-phan @cperdigou! I finished pushing changes for the 0.4 milestone. I have quite thoroughly tested. Could one of you be so nice and do a code review next week? It would be a great gift to publish the update for Christmas 🎄 !

**Comment by alexcombessie** [comment]
Hello @du-phan @cperdigou! Do you have an idea of your availability for a review? Thanks!

**Comment by alexcombessie** [comment]
Added a small bugfix for #16 and really minor UX rewording

**Comment by alexcombessie** [comment]
Hello @du-phan and happy holidays! Any chance this pull request could be merged this year?

**Review by du-phan — APPROVED** [review]
Functional tests seem good, merge to master

**Comment by alexcombessie** [comment]
Awesome ! Thanks @du-phan :) are you ok to push it to the store?

**Comment by du-phan** [comment]
Already did !

**Comment by alexcombessie** [comment]
Awesome! Then I guess we simply need to update the web page https://www.dataiku.com/product/plugins/forecast/

**Pull request merged**
